name: Build 

on:
 push:
  branches:
         main  
jobs:
  Build_and_Push:
   runs-on: ubuntu-latest
   timeout-minutes: 5
   steps:
   - name: Checkout Repository
     uses: actions/checkout@v2
   - name: Login to Docker Hub
     uses: docker/login-action@v2
     with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
 
   - name: Build Docker image
     run: docker build -t manuelanut/task_intership:latest . 

   - name: Tag Docker image
     run: docker tag manuelanut/task_intership:latest manuelanut/task_intership:$(git rev-parse --short HEAD)

   - name: Push Docker image
     run: docker push manuelanut/task_intership:latest && docker push mabuelanut/task_intership:$(git rev-parse --short HEAD) 
